import { Case, CaseExplainability, KGNavigationResult, KGStats, HottestPath, ConditionResult } from "@/types";

// Mock explainability data for demo — shows the 5-layer clinician transparency model
const mockExplainabilitySwahili: CaseExplainability = {
  language_banner: {
    patient_language: "sw",
    patient_language_name: "Swahili",
    detected_languages: ["sw", "en"],
    translation_used: true,
    code_switching_detected: true,
    translation_confidence: 0.72,
    detection_method: "whisper_asr",
    risk_level: "medium",
    risk_label: "Translation confidence moderate — code-switching detected between Swahili and English. Review original patient statements for clinical terms.",
    interpreter_recommended: false,
  },
  patient_evidence: [
    {
      turn_number: 1,
      original_text: "Nina maumivu makali sana ya tumbo, imeanza siku tatu zilizopita",
      language: "sw",
      timestamp: "2026-03-28T06:00:00Z",
      channel: "voice",
      label: "Original patient statement (Swahili)",
      english_translation: "I have very severe stomach pain, it started three days ago",
      translation_label: "System-translated to English (Claude)",
      translation_confidence: 0.85,
    },
    {
      turn_number: 2,
      original_text: "Ndiyo, nina homa pia. Joto langu ni kama 38 point 5. Na ninajisikia kichefuchefu",
      language: "sw",
      timestamp: "2026-03-28T06:01:30Z",
      channel: "voice",
      label: "Original patient statement (Swahili)",
      english_translation: "Yes, I also have a fever. My temperature is about 38.5. And I feel nauseous",
      translation_label: "System-translated to English (Claude)",
      translation_confidence: 0.88,
    },
    {
      turn_number: 3,
      original_text: "Pain iko hapa, right side ya chini. Inazidi nikisimama or nikitembea",
      language: "sw",
      timestamp: "2026-03-28T06:03:00Z",
      channel: "voice",
      label: "Original patient statement (Swahili + English code-switching)",
      english_translation: "The pain is here, on the lower right side. It gets worse when I stand or walk",
      translation_label: "System-translated to English (Claude)",
      translation_confidence: 0.78,
    },
  ],
  extraction: {
    items: [
      { type: "symptom", value: "abdominal pain", source: "patient_reported", source_turn: 1, confidence: 0.92, label: "Reported by patient" },
      { type: "symptom", value: "fever", source: "patient_reported", source_turn: 2, confidence: 0.95, label: "Reported by patient" },
      { type: "symptom", value: "nausea", source: "patient_reported", source_turn: 2, confidence: 0.88, label: "Reported by patient" },
      { type: "symptom", value: "RLQ tenderness", source: "ai_extracted", source_turn: 3, confidence: 0.75, label: "Inferred from location description" },
      { type: "severity", value: "7", display: "7/10", source: "ai_extracted", source_turn: 1, confidence: 0.7, label: "Estimated from 'makali sana' (very severe)" },
      { type: "duration", value: "3 days", source: "patient_reported", source_turn: 1, confidence: 0.93, label: "Reported by patient" },
      { type: "body_area", value: "Abdomen (RLQ)", source: "ai_extracted", source_turn: 3, confidence: 0.82, label: "Localized from patient description" },
    ],
    total_facts: 7,
    ai_extracted_count: 3,
    patient_reported_count: 4,
    label: "Structured clinical data (AI-assisted extraction from patient conversation)",
  },
  safety: {
    triage_level: "RED",
    triage_breakdown: {
      triage_level: "RED",
      base_score: 50,
      severity_score: 20,
      red_flag_score: 45,
      symptom_count_score: 9,
      duration_score: 5,
      kg_confidence_score: 8,
      country_tier_score: 30,
      total_priority: 80,
      explanation: "RED triage: persistent pain (3d) + fever + RLQ localization in Tier 3 country with limited surgical access.",
    },
    triggers: [
      { rule: "red_flag_keyword", severity: "warning", description: "Persistent abdominal pain > 48 hours", layer: "keyword" },
      { rule: "red_flag_keyword", severity: "warning", description: "Fever with localized pain", layer: "keyword" },
      { rule: "red_flag_rule", severity: "immediate", description: "RLQ tenderness pattern — possible appendicitis", layer: "pattern" },
    ],
    trigger_count: 3,
    emergency_detected: false,
    kg_confidence: 0.85,
    label: "Safety signals and rule triggers (deterministic, not AI opinion)",
  },
  ambiguity: {
    unresolved_items: [
      {
        type: "translation",
        flag: "code_switching_detected",
        context: "Patient mixed Swahili and English in turn 3 ('right side', 'or'). Clinical terms may have been expressed in English for precision.",
      },
      {
        type: "translation",
        flag: "clinically_sensitive_term_uncertain",
        context: "'makali sana' translated as 'very severe' — Swahili pain intensity mapping may differ from clinical pain scale.",
      },
    ],
    has_unresolved: true,
    count: 2,
    label: "Unresolved ambiguities — items the system could not determine safely",
  },
};

const mockExplainabilityHindi: CaseExplainability = {
  language_banner: {
    patient_language: "hi",
    patient_language_name: "Hindi",
    detected_languages: ["hi"],
    translation_used: true,
    code_switching_detected: false,
    translation_confidence: 0.65,
    detection_method: "whisper_asr",
    risk_level: "high",
    risk_label: "Low translation confidence for clinical content. Interpreter strongly recommended before clinical decisions.",
    interpreter_recommended: true,
  },
  patient_evidence: [
    {
      turn_number: 1,
      original_text: "मेरे सिर में बहुत तेज़ दर्द है, अचानक शुरू हुआ। आँखों में रोशनी बर्दाश्त नहीं होती",
      language: "hi",
      timestamp: "2026-03-28T05:25:00Z",
      channel: "voice",
      label: "Original patient statement (Hindi)",
      english_translation: "I have very severe headache, it started suddenly. I cannot tolerate light in my eyes",
      translation_label: "System-translated to English (Claude)",
      translation_confidence: 0.68,
    },
    {
      turn_number: 2,
      original_text: "गर्दन में अकड़न है और उल्टी जैसा लग रहा है। BP की दवाई लेता हूँ",
      language: "hi",
      timestamp: "2026-03-28T05:26:30Z",
      channel: "voice",
      label: "Original patient statement (Hindi)",
      english_translation: "There is stiffness in the neck and feeling like vomiting. I take BP medication",
      translation_label: "System-translated to English (Claude)",
      translation_confidence: 0.62,
    },
  ],
  extraction: {
    items: [
      { type: "symptom", value: "severe headache", source: "patient_reported", source_turn: 1, confidence: 0.9, label: "Reported by patient" },
      { type: "symptom", value: "photophobia", source: "ai_extracted", source_turn: 1, confidence: 0.72, label: "Inferred from light intolerance description" },
      { type: "symptom", value: "neck stiffness", source: "patient_reported", source_turn: 2, confidence: 0.85, label: "Reported by patient" },
      { type: "symptom", value: "nausea", source: "patient_reported", source_turn: 2, confidence: 0.88, label: "Reported by patient" },
      { type: "severity", value: "9", display: "9/10", source: "ai_extracted", source_turn: 1, confidence: 0.65, label: "Estimated from 'बहुत तेज़' (very intense)" },
      { type: "duration", value: "1 day", source: "ai_extracted", source_turn: 1, confidence: 0.7, label: "Inferred from 'suddenly started'" },
      { type: "body_area", value: "Head", source: "patient_reported", source_turn: 1, confidence: 0.95, label: "Reported by patient" },
    ],
    total_facts: 7,
    ai_extracted_count: 3,
    patient_reported_count: 4,
    label: "Structured clinical data (AI-assisted extraction from patient conversation)",
  },
  safety: {
    triage_level: "RED",
    triage_breakdown: {
      triage_level: "RED",
      base_score: 50,
      severity_score: 30,
      red_flag_score: 45,
      symptom_count_score: 12,
      duration_score: 10,
      kg_confidence_score: 7,
      country_tier_score: 20,
      total_priority: 92,
      explanation: "RED triage: thunderclap headache + neck stiffness + photophobia — meningitis/SAH pattern. Urgent referral.",
    },
    triggers: [
      { rule: "red_flag_rule", severity: "immediate", description: "Sudden severe headache (thunderclap pattern)", layer: "pattern" },
      { rule: "red_flag_keyword", severity: "immediate", description: "Neck stiffness with headache — meningeal signs", layer: "keyword" },
      { rule: "red_flag_keyword", severity: "warning", description: "Visual disturbance / photophobia", layer: "keyword" },
    ],
    trigger_count: 3,
    emergency_detected: true,
    kg_confidence: 0.89,
    label: "Safety signals and rule triggers (deterministic, not AI opinion)",
  },
  ambiguity: {
    unresolved_items: [
      {
        type: "translation",
        flag: "low_translation_confidence",
        context: "Overall translation confidence 65% — clinical nuance may be lost. Hindi pain descriptors ('तेज़ दर्द') map imprecisely to English severity scales.",
      },
      {
        type: "translation",
        flag: "clinically_sensitive_term_uncertain",
        context: "'अकड़न' (stiffness/rigidity) — uncertain whether this indicates meningismus or muscular tension. Clinical examination required.",
      },
      {
        type: "system",
        flag: "negation_uncertain",
        context: "Patient's statement about light tolerance uses double construction. Verify photophobia interpretation.",
      },
    ],
    has_unresolved: true,
    count: 3,
    label: "Unresolved ambiguities — items the system could not determine safely",
  },
};

const mockExplainabilityEnglish: CaseExplainability = {
  language_banner: {
    patient_language: "en",
    patient_language_name: "English",
    detected_languages: ["en"],
    translation_used: false,
    code_switching_detected: false,
    translation_confidence: 1.0,
    detection_method: "default",
    risk_level: "none",
    risk_label: "No translation required — patient communicated in English.",
    interpreter_recommended: false,
  },
  patient_evidence: [
    {
      turn_number: 1,
      original_text: "I've had this cough for about a week now. It's a dry cough, and sometimes my chest hurts when I cough",
      language: "en",
      timestamp: "2026-03-28T04:10:00Z",
      channel: "voice",
      label: "Original patient statement (English)",
    },
    {
      turn_number: 2,
      original_text: "No fever, no blood. Just the cough. Sometimes I get a bit short of breath when I walk fast",
      language: "en",
      timestamp: "2026-03-28T04:11:30Z",
      channel: "voice",
      label: "Original patient statement (English)",
    },
  ],
  extraction: {
    items: [
      { type: "symptom", value: "dry cough", source: "patient_reported", source_turn: 1, confidence: 0.95, label: "Reported by patient" },
      { type: "symptom", value: "chest discomfort", source: "patient_reported", source_turn: 1, confidence: 0.9, label: "Reported by patient" },
      { type: "symptom", value: "dyspnea on exertion", source: "ai_extracted", source_turn: 2, confidence: 0.78, label: "Inferred from 'short of breath when walking'" },
      { type: "severity", value: "4", display: "4/10", source: "ai_extracted", confidence: 0.75, label: "Estimated from mild descriptions" },
      { type: "duration", value: "7 days", source: "patient_reported", source_turn: 1, confidence: 0.95, label: "Reported by patient" },
      { type: "body_area", value: "Chest", source: "patient_reported", source_turn: 1, confidence: 0.95, label: "Reported by patient" },
    ],
    total_facts: 6,
    ai_extracted_count: 2,
    patient_reported_count: 4,
    label: "Structured clinical data (AI-assisted extraction from patient conversation)",
  },
  safety: {
    triage_level: "YELLOW",
    triage_breakdown: {
      triage_level: "YELLOW",
      base_score: 30,
      severity_score: 5,
      red_flag_score: 15,
      symptom_count_score: 9,
      duration_score: 5,
      kg_confidence_score: 5,
      country_tier_score: 20,
      total_priority: 55,
      explanation: "YELLOW triage: persistent cough >5 days with chest involvement. TB screening recommended given Tier 2 region.",
    },
    triggers: [
      { rule: "red_flag_keyword", severity: "warning", description: "Persistent cough > 5 days", layer: "keyword" },
    ],
    trigger_count: 1,
    emergency_detected: false,
    kg_confidence: 0.72,
    label: "Safety signals and rule triggers (deterministic, not AI opinion)",
  },
  ambiguity: {
    unresolved_items: [],
    has_unresolved: false,
    count: 0,
    label: "No unresolved ambiguities",
  },
};

export const mockCases: Case[] = [
  {
    caseId: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    patientAlias: "PT-9243",
    patientAge: 34,
    patientGender: "Female",
    clinicalDiagnosis: "Acute abdominal pain — rule out appendicitis",
    country: "Kenya",
    countryTier: 3,
    urgency: "High",
    symptomSummary: "Fever and persistent abdominal pain",
    painScore: 7,
    symptomDuration: "3 days",
    bodyArea: "Abdomen",
    imageUrls: [],
    consentGiven: true,
    submittedAt: "2026-03-28T06:07:57Z",
    redFlagIndicators: ["Persistent pain", "Fever", "RLQ tenderness"],
    priorityScore: 80.0,
    status: "pending_review",
    detectedLanguage: "sw",
    translationUsed: true,
    explainability: mockExplainabilitySwahili,
  },
  {
    caseId: "b2c3d4e5-f6a7-8901-bcde-f23456789012",
    patientAlias: "PT-1847",
    country: "Nigeria",
    countryTier: 3,
    urgency: "High",
    symptomSummary: "Severe headache with visual disturbances and neck stiffness",
    painScore: 9,
    symptomDuration: "1 day",
    bodyArea: "Head",
    imageUrls: [],
    consentGiven: true,
    submittedAt: "2026-03-28T05:30:00Z",
    redFlagIndicators: ["Sudden severe headache", "Neck stiffness", "Visual disturbance"],
    priorityScore: 92.0,
    status: "pending_review",
    detectedLanguage: "hi",
    translationUsed: true,
    explainability: mockExplainabilityHindi,
  },
  {
    caseId: "c3d4e5f6-a7b8-9012-cdef-345678901234",
    patientAlias: "PT-5612",
    country: "India",
    countryTier: 2,
    urgency: "Medium",
    symptomSummary: "Persistent cough with mild chest discomfort",
    painScore: 4,
    symptomDuration: "7 days",
    bodyArea: "Chest",
    imageUrls: [],
    consentGiven: true,
    submittedAt: "2026-03-28T04:15:00Z",
    redFlagIndicators: ["Persistent cough >5 days"],
    priorityScore: 55.0,
    status: "assigned",
    assignedDoctor: "Dr. Amara",
    detectedLanguage: "en",
    translationUsed: false,
    explainability: mockExplainabilityEnglish,
  },
  {
    caseId: "d4e5f6a7-b8c9-0123-defa-456789012345",
    patientAlias: "PT-3390",
    country: "Philippines",
    countryTier: 2,
    urgency: "Low",
    symptomSummary: "Mild skin rash on forearms, no pain",
    painScore: 1,
    symptomDuration: "5 days",
    bodyArea: "Skin",
    imageUrls: [],
    consentGiven: true,
    submittedAt: "2026-03-28T03:45:00Z",
    redFlagIndicators: [],
    priorityScore: 20.0,
    status: "responded",
    assignedDoctor: "Dr. Chen",
  },
  {
    caseId: "e5f6a7b8-c9d0-1234-efab-567890123456",
    patientAlias: "PT-7781",
    country: "Kenya",
    countryTier: 3,
    urgency: "Medium",
    symptomSummary: "Recurring joint pain in knees and ankles with swelling",
    painScore: 6,
    symptomDuration: "2 weeks",
    bodyArea: "Joints",
    imageUrls: [],
    consentGiven: true,
    submittedAt: "2026-03-27T22:00:00Z",
    redFlagIndicators: ["Joint swelling", "Fever"],
    priorityScore: 60.0,
    status: "pending_review",
  },
  {
    caseId: "f6a7b8c9-d0e1-2345-fabc-678901234567",
    patientAlias: "PT-4456",
    country: "Nigeria",
    countryTier: 3,
    urgency: "High",
    symptomSummary: "Chest pain radiating to left arm with shortness of breath",
    painScore: 8,
    symptomDuration: "2 hours",
    bodyArea: "Chest",
    imageUrls: [],
    consentGiven: true,
    submittedAt: "2026-03-28T06:45:00Z",
    redFlagIndicators: ["Chest pain", "Radiating to arm", "Shortness of breath", "Diaphoresis"],
    priorityScore: 95.0,
    status: "pending_review",
  },
  {
    caseId: "a7b8c9d0-e1f2-3456-abcd-789012345678",
    patientAlias: "PT-2198",
    country: "India",
    countryTier: 2,
    urgency: "Low",
    symptomSummary: "Intermittent stomach discomfort after meals",
    painScore: 3,
    symptomDuration: "10 days",
    bodyArea: "Abdomen",
    imageUrls: [],
    consentGiven: true,
    submittedAt: "2026-03-27T18:30:00Z",
    redFlagIndicators: [],
    priorityScore: 25.0,
    status: "assigned",
    assignedDoctor: "Dr. Müller",
  },
  {
    caseId: "b8c9d0e1-f2a3-4567-bcde-890123456789",
    patientAlias: "PT-6634",
    country: "Philippines",
    countryTier: 2,
    urgency: "Medium",
    symptomSummary: "High fever with body aches and fatigue for 4 days",
    painScore: 5,
    symptomDuration: "4 days",
    bodyArea: "Systemic",
    imageUrls: [],
    consentGiven: true,
    submittedAt: "2026-03-28T01:20:00Z",
    redFlagIndicators: ["High fever >4 days", "Dengue-endemic area"],
    priorityScore: 65.0,
    status: "pending_review",
  },
];

export const mockKGNavigation: KGNavigationResult = {
  conditions: [
    { name: "Acute Appendicitis", score: 0.85, specialty: "General Surgery" },
    { name: "Gastroenteritis", score: 0.72, specialty: "Internal Medicine" },
    { name: "Urinary Tract Infection", score: 0.45, specialty: "Urology" },
    { name: "Ovarian Torsion", score: 0.38, specialty: "Gynecology" },
  ],
  recommendedSpecialty: "General Surgery",
  followUpQuestions: [
    "Has the pain migrated from around the navel to the right lower quadrant?",
    "Is the pain worse with movement or coughing?",
    "Have you experienced loss of appetite recently?",
    "Any history of similar episodes?",
  ],
  bodySystemMapping: {
    Gastrointestinal: ["Abdominal pain", "Nausea"],
    "Immune / Systemic": ["Fever"],
    Urinary: ["Potential referred pain"],
  },
  graphPaths: [
    { from: "Fever", to: "Infection", weight: 0.9, type: "symptom-condition" },
    { from: "Abdominal Pain", to: "Acute Appendicitis", weight: 0.85, type: "symptom-condition" },
    { from: "Acute Appendicitis", to: "General Surgery", weight: 0.95, type: "condition-specialty" },
    { from: "Abdominal Pain", to: "Gastroenteritis", weight: 0.72, type: "symptom-condition" },
    { from: "Gastroenteritis", to: "Internal Medicine", weight: 0.8, type: "condition-specialty" },
    { from: "Fever", to: "Gastroenteritis", weight: 0.6, type: "symptom-condition" },
  ],
};

export const mockKGStats: KGStats = {
  totalNodes: 1247,
  totalEdges: 3891,
  learnedEdges: 456,
  specialties: [
    "General Surgery",
    "Internal Medicine",
    "Cardiology",
    "Neurology",
    "Pediatrics",
    "Dermatology",
    "Urology",
    "Gynecology",
    "Pulmonology",
    "Orthopedics",
    "Emergency Medicine",
    "Psychiatry",
  ],
  lastUpdated: "2026-03-28T05:00:00Z",
};

export const mockHottestPaths: HottestPath[] = [
  { source: "Chest Pain", target: "Acute Coronary Syndrome", conductivity: 0.94, pathType: "symptom → condition" },
  { source: "Fever + Headache", target: "Meningitis", conductivity: 0.89, pathType: "symptom → condition" },
  { source: "Acute Coronary Syndrome", target: "Cardiology", conductivity: 0.97, pathType: "condition → specialty" },
  { source: "Abdominal Pain + Fever", target: "Appendicitis", conductivity: 0.86, pathType: "symptom → condition" },
  { source: "Shortness of Breath", target: "Pulmonary Embolism", conductivity: 0.82, pathType: "symptom → condition" },
  { source: "Rash + Fever", target: "Dengue Fever", conductivity: 0.80, pathType: "symptom → condition" },
  { source: "Joint Pain + Swelling", target: "Rheumatoid Arthritis", conductivity: 0.78, pathType: "symptom → condition" },
  { source: "Meningitis", target: "Neurology", conductivity: 0.95, pathType: "condition → specialty" },
  { source: "Cough + Hemoptysis", target: "Tuberculosis", conductivity: 0.76, pathType: "symptom → condition" },
  { source: "Pulmonary Embolism", target: "Pulmonology", conductivity: 0.91, pathType: "condition → specialty" },
];

export function getMockConditions(symptom: string): ConditionResult {
  const conditionMap: Record<string, ConditionResult> = {
    fever: {
      symptom: "fever",
      conditions: [
        { name: "Malaria", probability: 0.75, severity: "High" },
        { name: "Dengue Fever", probability: 0.68, severity: "High" },
        { name: "Urinary Tract Infection", probability: 0.55, severity: "Medium" },
        { name: "Upper Respiratory Infection", probability: 0.50, severity: "Low" },
        { name: "Typhoid Fever", probability: 0.42, severity: "High" },
      ],
    },
    headache: {
      symptom: "headache",
      conditions: [
        { name: "Meningitis", probability: 0.60, severity: "High" },
        { name: "Migraine", probability: 0.72, severity: "Medium" },
        { name: "Tension Headache", probability: 0.80, severity: "Low" },
        { name: "Subarachnoid Hemorrhage", probability: 0.25, severity: "High" },
      ],
    },
    cough: {
      symptom: "cough",
      conditions: [
        { name: "Tuberculosis", probability: 0.45, severity: "High" },
        { name: "Pneumonia", probability: 0.60, severity: "High" },
        { name: "Bronchitis", probability: 0.70, severity: "Medium" },
        { name: "Asthma", probability: 0.55, severity: "Medium" },
        { name: "Common Cold", probability: 0.85, severity: "Low" },
      ],
    },
    "chest pain": {
      symptom: "chest pain",
      conditions: [
        { name: "Acute Coronary Syndrome", probability: 0.65, severity: "High" },
        { name: "Pulmonary Embolism", probability: 0.40, severity: "High" },
        { name: "Costochondritis", probability: 0.50, severity: "Low" },
        { name: "GERD", probability: 0.55, severity: "Low" },
      ],
    },
  };

  const key = symptom.toLowerCase().trim();
  return (
    conditionMap[key] || {
      symptom: key,
      conditions: [
        { name: "Condition data unavailable", probability: 0, severity: "Low" },
      ],
    }
  );
}
