// ============================================================
// mockData/patientCases.ts
// Mock Patient Cases — 8 entries covering all tiers/urgencies
//
// DATA SOURCE LEGEND
//   [INTAKE]  = set during AI phone/SMS intake, READ-ONLY in portal
//   [PORTAL]  = set/updated by the doctor portal
//   [SYSTEM]  = generated by the system at case creation
//   [AI]      = generated by WHO ICD-11 triage AI
// ============================================================

import {
  CountryTier,
  DoctorDecisionStatus,
  PatientCase,
  UrgencyLevel,
} from "../types";

// Extended type with AI fields used in case detail view
export interface ExtendedPatientCase extends PatientCase {
  aiStructuredNotes?: AiNote[];
  redFlagIndicators?: string[];
}

export interface AiNote {
  category: string;
  finding: string;
  icdCode?: string;
  confidence?: number;
}

export const MOCK_PATIENT_CASES: ExtendedPatientCase[] = [
  // ──────────────────────────────────────────────────────────
  // CASE 1 | EMERGENCY | Tier 3 | Kenya | Not reviewed
  // ──────────────────────────────────────────────────────────
  {
    // [SYSTEM]
    caseId: "case-A3F2",
    createdAt: "2025-07-14T06:12:00Z",
    updatedAt: "2025-07-14T06:12:00Z",
    countryTier: CountryTier.TIER_3,

    // [INTAKE] Identity & Consent
    patientAlias: "Patient #A3F2",
    phoneNumber: "+254***7821",
    countryCode: "KE",
    country: "Kenya",
    consentGiven: true,
    consentTimestamp: "2025-07-14T06:10:33Z",

    // [INTAKE] Symptoms
    symptomSummary:
      "Patient reports sudden onset of severe chest pain radiating to the left arm, accompanied by profuse sweating and shortness of breath lasting approximately 40 minutes. No prior cardiac history reported.",
    affectedBodyArea: ["chest", "left arm"],
    painScore: 9,
    symptomDurationDays: 0,
    urgencyLevel: UrgencyLevel.EMERGENCY,

    // [INTAKE] Media
    uploadedImageUrls: [],
    intakeChannel: "VOICE",
    intakeLanguage: "sw",

    // [AI] Triage notes
    redFlagIndicators: [
      "Chest pain radiating to left arm — possible ACS/MI pattern",
      "Profuse sweating combined with dyspnea — hemodynamic instability risk",
      "Acute onset < 1 hour — time-critical intervention window",
    ],
    aiStructuredNotes: [
      {
        category: "Cardiovascular",
        finding: "Symptom constellation consistent with possible Acute Myocardial Infarction (STEMI/NSTEMI). Immediate ECG and troponin required.",
        icdCode: "BA80",
        confidence: 88,
      },
      {
        category: "Respiratory",
        finding: "Shortness of breath may indicate acute pulmonary edema secondary to cardiac event. Oxygen saturation monitoring critical.",
        icdCode: "CA22",
        confidence: 72,
      },
    ],

    // [PORTAL] Doctor review state
    doctorReviewed: 0,
    doctorReviewedAt: null,
    doctorId: null,
    doctorDecisionStatus: DoctorDecisionStatus.PENDING,
    outcomeSubmission: null,
  },

  // ──────────────────────────────────────────────────────────
  // CASE 2 | EMERGENCY | Tier 4 | South Sudan | Not reviewed
  // ──────────────────────────────────────────────────────────
  {
    caseId: "case-B7C1",
    createdAt: "2025-07-14T07:02:00Z",
    updatedAt: "2025-07-14T07:02:00Z",
    countryTier: CountryTier.TIER_4,

    patientAlias: "Patient #B7C1",
    phoneNumber: "+211***3340",
    countryCode: "SS",
    country: "South Sudan",
    consentGiven: true,
    consentTimestamp: "2025-07-14T07:00:14Z",

    symptomSummary:
      "Patient is a caregiver reporting on behalf of a child, approximately 4 years old, presenting with high fever (estimated 40°C), convulsions, and loss of consciousness for approximately 10 minutes. Possible malaria exposure in the past week.",
    affectedBodyArea: ["head", "full body"],
    painScore: 8,
    symptomDurationDays: 2,
    urgencyLevel: UrgencyLevel.EMERGENCY,

    uploadedImageUrls: [],
    intakeChannel: "VOICE",
    intakeLanguage: "en",

    redFlagIndicators: [
      "Convulsions in a child with high fever — febrile seizure or cerebral malaria",
      "Loss of consciousness — CNS involvement, neurological emergency",
      "Malaria exposure area — P. falciparum risk, cerebral malaria possibility",
    ],
    aiStructuredNotes: [
      {
        category: "Infectious Disease",
        finding: "Fever + convulsions + recent malaria exposure in endemic area. Cerebral malaria (P. falciparum) must be ruled out urgently.",
        icdCode: "1F40",
        confidence: 85,
      },
      {
        category: "Neurology",
        finding: "Convulsions with transient loss of consciousness in a febrile child. Febrile seizure vs. meningitis vs. encephalitis differential.",
        icdCode: "8A60",
        confidence: 78,
      },
    ],

    doctorReviewed: 0,
    doctorReviewedAt: null,
    doctorId: null,
    doctorDecisionStatus: DoctorDecisionStatus.PENDING,
    outcomeSubmission: null,
  },

  // ──────────────────────────────────────────────────────────
  // CASE 3 | HIGH | Tier 2 | Nigeria | Not reviewed
  // Images submitted via SMS
  // ──────────────────────────────────────────────────────────
  {
    caseId: "case-D9E5",
    createdAt: "2025-07-14T05:45:00Z",
    updatedAt: "2025-07-14T05:45:00Z",
    countryTier: CountryTier.TIER_2,

    patientAlias: "Patient #D9E5",
    phoneNumber: "+234***0912",
    countryCode: "NG",
    country: "Nigeria",
    consentGiven: true,
    consentTimestamp: "2025-07-14T05:43:00Z",

    symptomSummary:
      "Adult male, late 30s, reports persistent high fever for 4 days (self-measured ~39.5°C), joint pain, and a red rash spreading from the trunk to limbs. No travel history. Has not taken any medication.",
    affectedBodyArea: ["trunk", "limbs", "joints"],
    painScore: 7,
    symptomDurationDays: 4,
    urgencyLevel: UrgencyLevel.HIGH,

    // Images received via SMS intake
    uploadedImageUrls: [
      "https://mock-storage.telehealth.io/cases/D9E5/rash-photo-1.jpg",
      "https://mock-storage.telehealth.io/cases/D9E5/rash-photo-2.jpg",
    ],
    intakeChannel: "COMBINED",
    intakeLanguage: "en",

    redFlagIndicators: [
      "Spreading maculopapular rash with fever — possible dengue, typhoid, or meningococcal",
      "Fever > 4 days without treatment — risk of complications increasing",
    ],
    aiStructuredNotes: [
      {
        category: "Infectious Disease",
        finding: "Fever + diffuse rash + arthralgia differential includes dengue fever, typhoid, arboviral infection, or early meningococcal disease. Image review recommended.",
        icdCode: "1D2Z",
        confidence: 81,
      },
      {
        category: "Dermatology",
        finding: "Patient-submitted images show maculopapular erythema spreading centrifugally from trunk. No petechiae visible. Consistent with viral exanthem.",
        icdCode: "EA90",
        confidence: 69,
      },
    ],

    doctorReviewed: 0,
    doctorReviewedAt: null,
    doctorId: null,
    doctorDecisionStatus: DoctorDecisionStatus.PENDING,
    outcomeSubmission: null,
  },

  // ──────────────────────────────────────────────────────────
  // CASE 4 | HIGH | Tier 2 | Brazil | In review
  // ──────────────────────────────────────────────────────────
  {
    caseId: "case-F2G8",
    createdAt: "2025-07-13T22:30:00Z",
    updatedAt: "2025-07-14T08:05:00Z",
    countryTier: CountryTier.TIER_2,

    patientAlias: "Patient #F2G8",
    phoneNumber: "+55***4478",
    countryCode: "BR",
    country: "Brazil",
    consentGiven: true,
    consentTimestamp: "2025-07-13T22:28:45Z",

    symptomSummary:
      "Female patient, mid-50s, with known type 2 diabetes reports dizziness, blurred vision, increased thirst, and frequent urination over the past 3 days. Self-reported blood sugar reading was 320 mg/dL this morning.",
    affectedBodyArea: ["eyes", "head"],
    painScore: 4,
    symptomDurationDays: 3,
    urgencyLevel: UrgencyLevel.HIGH,

    uploadedImageUrls: [],
    intakeChannel: "VOICE",
    intakeLanguage: "pt",

    redFlagIndicators: [
      "Blood glucose 320 mg/dL — hyperglycaemic crisis threshold",
      "Blurred vision in diabetic patient — risk of diabetic retinopathy or DKA",
    ],
    aiStructuredNotes: [
      {
        category: "Endocrinology",
        finding: "Uncontrolled T2DM with glucose 320 mg/dL. Risk of hyperosmolar hyperglycaemic state (HHS) or diabetic ketoacidosis (DKA). Urgent glucose management needed.",
        icdCode: "5A11",
        confidence: 91,
      },
      {
        category: "Ophthalmology",
        finding: "Acute blurred vision in established diabetic — acute hyperglycaemic lens swelling vs. early diabetic retinopathy. Fundoscopy recommended.",
        icdCode: "9B71",
        confidence: 65,
      },
    ],

    doctorReviewed: 1,
    doctorReviewedAt: "2025-07-14T08:05:00Z",
    doctorId: "doc-001",
    doctorDecisionStatus: DoctorDecisionStatus.IN_REVIEW,
    outcomeSubmission: null,
  },

  // ──────────────────────────────────────────────────────────
  // CASE 5 | MEDIUM | Tier 3 | Tanzania | Completed
  // ──────────────────────────────────────────────────────────
  {
    caseId: "case-H5K3",
    createdAt: "2025-07-13T18:00:00Z",
    updatedAt: "2025-07-14T09:00:00Z",
    countryTier: CountryTier.TIER_3,

    patientAlias: "Patient #H5K3",
    phoneNumber: "+255***6601",
    countryCode: "TZ",
    country: "Tanzania",
    consentGiven: true,
    consentTimestamp: "2025-07-13T17:58:22Z",

    symptomSummary:
      "Adult female, early 30s, reports lower abdominal pain (moderate), abnormal vaginal discharge, and mild fever for 6 days. No recent sexual health screening. Breastfeeding a 6-month-old infant.",
    affectedBodyArea: ["lower abdomen", "pelvis"],
    painScore: 5,
    symptomDurationDays: 6,
    urgencyLevel: UrgencyLevel.MEDIUM,

    uploadedImageUrls: [],
    intakeChannel: "SMS",
    intakeLanguage: "sw",

    aiStructuredNotes: [
      {
        category: "Gynaecology",
        finding: "Presentation consistent with possible pelvic inflammatory disease (PID). Physical examination and STI swabs required — not possible via telehealth.",
        icdCode: "GA10",
        confidence: 77,
      },
    ],

    doctorReviewed: 1,
    doctorReviewedAt: "2025-07-14T09:00:00Z",
    doctorId: "doc-001",
    doctorDecisionStatus: DoctorDecisionStatus.COMPLETED,
    outcomeSubmission: {
      submittedAt: "2025-07-14T09:15:00Z",
      submittedByDoctorId: "doc-001",
      recommendedAction: "REFER_LOCAL" as any,
      referralSuggestion: "Nearest district hospital with reproductive health clinic",
      referralUrgency: "URGENT",
      followUpAdvice:
        "Seek in-person evaluation within 48 hours. Avoid self-medicating. Continue breastfeeding unless advised otherwise by attending physician.",
      generalNotes:
        "Presentation consistent with possible pelvic inflammatory disease. Requires physical examination and lab work not available via telehealth. Referred to local facility.",
      estimatedFollowUpDays: 3,
      languageOfCommunication: "en",
    },
  },

  // ──────────────────────────────────────────────────────────
  // CASE 6 | MEDIUM | Tier 4 | Mali | Not reviewed
  // ──────────────────────────────────────────────────────────
  {
    caseId: "case-J1L9",
    createdAt: "2025-07-14T04:20:00Z",
    updatedAt: "2025-07-14T04:20:00Z",
    countryTier: CountryTier.TIER_4,

    patientAlias: "Patient #J1L9",
    phoneNumber: "+223***5503",
    countryCode: "ML",
    country: "Mali",
    consentGiven: true,
    consentTimestamp: "2025-07-14T04:18:55Z",

    symptomSummary:
      "Elderly male, estimated 65+, reports persistent dry cough for 3 weeks, night sweats, and gradual unintentional weight loss. No known TB exposure reported, but lives in a densely populated rural area.",
    affectedBodyArea: ["lungs", "chest"],
    painScore: 3,
    symptomDurationDays: 21,
    urgencyLevel: UrgencyLevel.MEDIUM,

    uploadedImageUrls: [],
    intakeChannel: "VOICE",
    intakeLanguage: "fr",

    redFlagIndicators: [
      "Classic TB triad: chronic cough + night sweats + weight loss (>3 weeks)",
      "High-density rural area — community TB transmission risk",
    ],
    aiStructuredNotes: [
      {
        category: "Pulmonology",
        finding: "Chronic productive cough ≥3 weeks + constitutional symptoms (night sweats, weight loss) in elderly patient from endemic area. Active TB must be excluded.",
        icdCode: "1B10",
        confidence: 83,
      },
    ],

    doctorReviewed: 0,
    doctorReviewedAt: null,
    doctorId: null,
    doctorDecisionStatus: DoctorDecisionStatus.PENDING,
    outcomeSubmission: null,
  },

  // ──────────────────────────────────────────────────────────
  // CASE 7 | LOW | Tier 2 | India | Completed
  // Multiple SMS images of skin lesion
  // ──────────────────────────────────────────────────────────
  {
    caseId: "case-M4N6",
    createdAt: "2025-07-13T12:00:00Z",
    updatedAt: "2025-07-14T07:30:00Z",
    countryTier: CountryTier.TIER_2,

    patientAlias: "Patient #M4N6",
    phoneNumber: "+91***8824",
    countryCode: "IN",
    country: "India",
    consentGiven: true,
    consentTimestamp: "2025-07-13T11:58:10Z",

    symptomSummary:
      "Young adult male, early 20s, reports a painful skin lesion on the right forearm present for 5 days. Lesion appears red, swollen, and has a small pus-filled center. Mild fever (37.8°C) reported. No known allergies.",
    affectedBodyArea: ["right forearm"],
    painScore: 4,
    symptomDurationDays: 5,
    urgencyLevel: UrgencyLevel.LOW,

    // 3 images sent via SMS during intake
    uploadedImageUrls: [
      "https://mock-storage.telehealth.io/cases/M4N6/forearm-lesion-1.jpg",
      "https://mock-storage.telehealth.io/cases/M4N6/forearm-lesion-2.jpg",
      "https://mock-storage.telehealth.io/cases/M4N6/forearm-lesion-3.jpg",
    ],
    intakeChannel: "COMBINED",
    intakeLanguage: "hi",

    aiStructuredNotes: [
      {
        category: "Dermatology",
        finding: "Patient-submitted SMS images show a localised erythematous nodule with central pustulation on the right forearm. Consistent with furuncle (boil). No cellulitis spread visible.",
        icdCode: "1B72",
        confidence: 89,
      },
    ],

    doctorReviewed: 1,
    doctorReviewedAt: "2025-07-14T07:30:00Z",
    doctorId: "doc-002",
    doctorDecisionStatus: DoctorDecisionStatus.COMPLETED,
    outcomeSubmission: {
      submittedAt: "2025-07-14T07:45:00Z",
      submittedByDoctorId: "doc-002",
      recommendedAction: "LIMITED_TREATMENT" as any,
      treatmentNotes:
        "Advise warm compress to the area 3x daily. Keep wound clean and covered. OTC antiseptic (povidone-iodine) may be applied.",
      referralSuggestion:
        "Visit a local clinic if no improvement within 48–72 hours or if redness spreads.",
      referralUrgency: "ROUTINE",
      followUpAdvice:
        "Monitor the lesion daily. Do not squeeze or puncture. If fever rises above 38.5°C, seek in-person care immediately.",
      generalNotes:
        "Presentation consistent with minor furuncle (boil). Images reviewed. No signs of systemic spread at this stage.",
      estimatedFollowUpDays: 3,
      languageOfCommunication: "en",
    },
  },

  // ──────────────────────────────────────────────────────────
  // CASE 8 | LOW | Tier 3 | Bangladesh | Escalated
  // ──────────────────────────────────────────────────────────
  {
    caseId: "case-P8Q2",
    createdAt: "2025-07-13T09:15:00Z",
    updatedAt: "2025-07-14T06:00:00Z",
    countryTier: CountryTier.TIER_3,

    patientAlias: "Patient #P8Q2",
    phoneNumber: "+880***2217",
    countryCode: "BD",
    country: "Bangladesh",
    consentGiven: true,
    consentTimestamp: "2025-07-13T09:13:40Z",

    symptomSummary:
      "Female patient, mid-40s, reports mild but recurring headaches (frontal region) over the past 2 weeks. Also mentions intermittent blurred vision and occasional nausea. No history of hypertension reported, but patient is unsure of last blood pressure reading.",
    affectedBodyArea: ["head", "eyes"],
    painScore: 3,
    symptomDurationDays: 14,
    urgencyLevel: UrgencyLevel.LOW,

    uploadedImageUrls: [],
    intakeChannel: "VOICE",
    intakeLanguage: "bn",

    redFlagIndicators: [
      "Blurred vision + headache + nausea triad — possible hypertensive urgency or early glaucoma",
      "Unknown BP status in middle-aged female — undiagnosed hypertension risk",
    ],
    aiStructuredNotes: [
      {
        category: "Ophthalmology",
        finding: "Recurring frontal headache with intermittent blurred vision. Fundoscopy needed to rule out papilloedema. Possible acute angle-closure glaucoma.",
        icdCode: "9C61",
        confidence: 64,
      },
      {
        category: "Cardiology",
        finding: "Unknown BP in symptomatic patient with headache and visual changes. Hypertensive urgency or emergency must be ruled out with BP measurement.",
        icdCode: "BA00",
        confidence: 71,
      },
    ],

    doctorReviewed: 1,
    doctorReviewedAt: "2025-07-14T06:00:00Z",
    doctorId: "doc-002",
    doctorDecisionStatus: DoctorDecisionStatus.ESCALATED,
    outcomeSubmission: {
      submittedAt: "2025-07-14T06:20:00Z",
      submittedByDoctorId: "doc-002",
      recommendedAction: "REFER_SPECIALIST" as any,
      referralSuggestion:
        "Ophthalmologist and/or hypertension specialist at district hospital",
      referralUrgency: "URGENT",
      followUpAdvice:
        "Please attend the nearest district hospital for a blood pressure check and eye examination. Do not delay if headaches worsen or vision deteriorates further.",
      generalNotes:
        "Combination of frontal headache, blurred vision, and nausea over 2 weeks raises concern for possible hypertensive episode or early glaucoma. Physical examination and BP measurement required. Case escalated to specialist referral pathway.",
      estimatedFollowUpDays: 2,
      languageOfCommunication: "en",
    },
  },
];
